# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "common.sh"

  config.vm.provision "shell", privileged: false, path: "rpmbuild-setup.sh"

  config.vm.box = "centos/7"
  config.vm.hostname = "rpmbuild-centos7"
  config.vm.network "private_network", ip: "192.168.33.14"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "rpmbuild-centos7"
    vb.gui = false
    vb.cpus = 1
    vb.memory = "2048"
  end

end
