# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "common.sh"
  config.vm.provision "file", source: "files", destination: "files"

  config.vm.define "k8s-vm" do |k8sVM|
    k8sVM.vm.box = "centos/7"
    k8sVM.vm.hostname = "k8s-vm"
    k8sVM.vm.network "private_network", ip: "192.168.33.10"

    k8sVM.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-vm"
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
    end

    k8sVM.vm.provision "shell", path: "setup_k8s.sh"
    k8sVM.vm.provision "shell", privileged: false, path: "post_setup_k8s.sh"

  end

end
