# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "common.sh"

  config.vm.provision "shell", path: "iptables-redirect-demo.sh"

  config.vm.box = "centos/7"
  config.vm.hostname = "iptables-centos7"
  config.vm.network "private_network", ip: "192.168.33.12"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "iptables-centos7"
    vb.gui = false
    vb.cpus = 1
    vb.memory = "2048"
  end

end
