run-playbook:
	ansible-playbook ansible/playbook.yml -i ansible/inventory --private-key=$(HOME)/.vagrant.d/insecure_private_key --user=vagrant --become --ssh-common-args='-o StrictHostKeyChecking=no'
