# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.provision "shell", path: "common.sh"

  config.vm.provision "shell", path: "install-zookeeper.sh"

  config.vm.provision "shell", path: "install-kafka.sh"

  config.vm.define "kafka-host1" do |c|
    c.vm.box = "centos/7"
    c.vm.hostname = "kafka-host1"

    c.vm.network "private_network", ip: "192.168.2.131"

    c.vm.provision "shell", path: "config-zookeeper-host1.sh"

    c.vm.provision "shell", path: "config-kafka-host1.sh"

    c.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--name", "kafka-host1"]
    end # end provider
  end

  config.vm.define "kafka-host2" do |c|
    c.vm.box = "centos/7"
    c.vm.hostname = "kafka-host2"

    c.vm.network "private_network", ip: "192.168.2.131"

    c.vm.provision "shell", path: "config-zookeeper-host2.sh"

    c.vm.provision "shell", path: "config-kafka-host2.sh"

    c.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--name", "kafka-host2"]
    end # end provider
  end

  config.vm.define "kafka-host3" do |c|
    c.vm.box = "centos/7"
    c.vm.hostname = "kafka-host3"

    c.vm.network "private_network", ip: "192.168.2.131"

    c.vm.provision "shell", path: "config-zookeeper-host3.sh"

    c.vm.provision "shell", path: "config-kafka-host3.sh"

    c.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--name", "kafka-host3"]
    end # end provider
  end

end
